### PR TITLE
Added all status items provided by haproxy 1.5

### PR DESCRIPTION
**Pull request by noamik**
The items and graphs provided by this commit have been generated semi-automatically. The next step will be to use zabbix_trapper instead of zabbix_agent items to collect and transfer the information. Even with only a handful of frontends and backends hundreds of items will be created.

If you reject this pull request please note that your current UserParameter "haproxy.stats.scur" doesn't return the session rate. It returns the current sessions, which is different from the actual session rate. The session rate is key number 34, not key number 4.

### CODE REVIEW

**Comment by anapsix** [comment]
Hey @noamik, appreciate the work..
I'm merging this for immediate availability.
But heads-up, I'm going to see if I can move those into the script. I think it would look cleaner in a script, rather than individually..
Though, thinking more about it.. does adding another component actually makes a simplification(?)..

**Comment by noamik** [comment]
@anapsix The reason why I didn't make a more general approach myself is that you can't handle all items the same. Some are unsigned integers, some are signed and some are characters. To make matters worse many of these items will be empty at times. Not for all of them replacing empty with zero makes sense.

Personally I prefer to look into adjusting the transfer of the data. Atm each item is polled individually. That's bad on multiple levels. First of all it means LOTS of polling. I also don't like the fact that the data of the items currently isn't from the same timestamp. To cure both problems I want to replace this with a single poller item for all the data. Then I want to have each item be handled by a trapper.

**Comment by anapsix** [comment]
@noamik checkout out commit c9228dc436574939b3b75630bf04375281390abf, which includes new script, that caches the haproxy stats data and supports defaults.
this commit includes your defaults, unless I've messed them up.

**Comment by anapsix** [comment]
let me know how it works out..

**Pull request merged**
